export const homeObjTwo = {
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Project",
  project: "Project",
  projectTitle: "O Days",
  description: "O Days",
  year: 2022,
  deliverable1: "Web development",
  buttonLabel: "Visit Website",
  alt: "Anne",
  dark: false,
  primary: false,
  darkText: true,
};
