export const homeObjTwo = {
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Project",
  project: "Project",
  projectTitle: "Jobspire",
  description: "Jobspire",
  year: 2023,
  deliverable1: "UX design",
  deliverable2: "UI design",
  buttonLabel: "Visit Website",
  alt: "Anne",
  dark: false,
  primary: false,
  darkText: true,
  img: require("../../../images/jobspire/jobspire-desk.png").default,
  img2: require("../../../images/jobspire/mobile-img.png").default,
  img3: require("../../../images/jobspire/jobspire-desk3.png").default,
  img4: require("../../../images/jobspire/jobspire-mobile.png").default,
};
